---
- name: "Installation de nginx"
  become: yes
  hosts: prod
  tasks:
    - name: "installation of epel-release"
      yum:
        name: "epel-release"
        state: present
    - name: "installation de nginx"
      yum:
        name: nginx
        state: latest
    - name: "Demarrage du service"
      service: 
        name: nginx
        state: started
        enabled: yes
...       
