---
- name: "Uninstall de nginx"
  become: yes
  hosts: prod
  tasks:
    - name: "stop service"
      service:
        name: nginx
        state:  stopped
        enabled: yes
    - name: "remove nginx"
      yum:
        name: nginx
        state: absent
    - name: "Allow http connections"
      firewalld:
        service: "http"
        permanent: yes
        immediate: yes
        state: disabled
...
